import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

const SAMPLE_REQUESTS = [
  // 1. OPEN requests
  {
    reference: 'RET-2026-A1B2C',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav.sharma@example.com',
    customerPhone: '+91 98765 43210',
    orderId: 'ORD-10001',
    itemSku: 'SKU-SHIRT-BLU-M',
    itemName: 'Classic Oxford Cotton Shirt - Blue (M)',
    quantity: 1,
    reason: 'SIZE_ISSUE',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-20T09:30:00Z'),
    notes: [
      {
        authorName: 'Support Bot',
        content: 'Return request submitted by customer via portal.',
        createdAt: new Date('2026-08-20T09:30:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-D3E4F',
    customerName: 'Priya Patel',
    customerEmail: 'priya.patel@example.com',
    customerPhone: '+91 91234 56789',
    orderId: 'ORD-10002',
    itemSku: 'SKU-HEADPHONES-PRO',
    itemName: 'Wireless Noise-Canceling Headphones - Black',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-21T11:15:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Customer reported right earcup has no audio output upon unboxing.',
        createdAt: new Date('2026-08-21T11:20:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-G5H6J',
    customerName: 'Rohan Mehta',
    customerEmail: 'rohan.mehta@example.com',
    customerPhone: '+91 99887 76655',
    orderId: 'ORD-10003',
    itemSku: 'SKU-RUN-SHOES-9',
    itemName: 'Pro Endurance Running Shoes - Size 9',
    quantity: 1,
    reason: 'WRONG_ITEM',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-22T08:00:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-K7M8N',
    customerName: 'Sneha Rao',
    customerEmail: 'sneha.rao@example.com',
    customerPhone: '+91 97654 32109',
    orderId: 'ORD-10004',
    itemSku: 'SKU-SILK-DRESS-S',
    itemName: 'Floral Print Silk Maxi Dress (S)',
    quantity: 2,
    reason: 'NOT_AS_DESCRIBED',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-22T14:45:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-P9Q1R',
    customerName: 'Vikram Joshi',
    customerEmail: 'vikram.joshi@example.com',
    customerPhone: '+91 94567 89012',
    orderId: 'ORD-10005',
    itemSku: 'SKU-COFFEE-MUG-CER',
    itemName: 'Ceramic Artisan Coffee Mug 350ml',
    quantity: 4,
    reason: 'CHANGED_MIND',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-23T10:10:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-S2T3U',
    customerName: 'Ananya Gupta',
    customerEmail: 'ananya.gupta@example.com',
    customerPhone: '+91 93456 78901',
    orderId: 'ORD-10006',
    itemSku: 'SKU-YOGA-MAT-6MM',
    itemName: 'Eco-Friendly Yoga Mat 6mm - Teal',
    quantity: 1,
    reason: 'SIZE_ISSUE',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-23T16:20:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-V4W5X',
    customerName: 'Karan Singh',
    customerEmail: 'karan.singh@example.com',
    customerPhone: '+91 92345 67890',
    orderId: 'ORD-10007',
    itemSku: 'SKU-LEATHER-BELT-34',
    itemName: 'Genuine Full-Grain Leather Belt (34)',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-24T09:00:00Z'),
    notes: [],
  },

  // 2. IN_REVIEW requests
  {
    reference: 'RET-2026-Y6Z7A',
    customerName: 'Meera Nambiar',
    customerEmail: 'meera.nambiar@example.com',
    customerPhone: '+91 91234 87654',
    orderId: 'ORD-10008',
    itemSku: 'SKU-SMARTWATCH-ULTRA',
    itemName: 'FitPulse Smartwatch Ultra - Silver',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-19T13:00:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Moved to In Review. Requested high-res photos of package damage from customer.',
        createdAt: new Date('2026-08-19T13:15:00Z'),
      },
      {
        authorName: 'Deepak (Lead)',
        content: 'Customer sent unboxing video showing broken screen on arrival.',
        createdAt: new Date('2026-08-20T10:45:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-B8C9D',
    customerName: 'Aditya Verma',
    customerEmail: 'aditya.verma@example.com',
    customerPhone: '+91 98123 45678',
    orderId: 'ORD-10009',
    itemSku: 'SKU-DENIM-JEANS-32',
    itemName: 'Slim Tapered Stretch Denim Jeans (32/32)',
    quantity: 2,
    reason: 'SIZE_ISSUE',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-20T15:30:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Checking inventory for size 34 replacement before proceeding.',
        createdAt: new Date('2026-08-21T09:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-E1F2G',
    customerName: 'Pooja Bhatt',
    customerEmail: 'pooja.bhatt@example.com',
    customerPhone: '+91 97012 34567',
    orderId: 'ORD-10010',
    itemSku: 'SKU-BLENDER-750W',
    itemName: 'NutriBlend 750W High-Speed Kitchen Blender',
    quantity: 1,
    reason: 'NOT_AS_DESCRIBED',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-21T17:00:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Customer received 500W model instead of advertised 750W. Verifying warehouse dispatch log.',
        createdAt: new Date('2026-08-22T08:30:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-H3J4K',
    customerName: 'Rahul Kapoor',
    customerEmail: 'rahul.kapoor@example.com',
    customerPhone: '+91 96543 21098',
    orderId: 'ORD-10011',
    itemSku: 'SKU-KEYBOARD-MECH-RGB',
    itemName: 'Tenkeyless RGB Mechanical Gaming Keyboard',
    quantity: 1,
    reason: 'WRONG_ITEM',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-22T11:45:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Customer received blue switch model instead of red silent switch.',
        createdAt: new Date('2026-08-22T12:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-M5N6P',
    customerName: 'Ishaan Nair',
    customerEmail: 'ishaan.nair@example.com',
    customerPhone: '+91 95432 10987',
    orderId: 'ORD-10012',
    itemSku: 'SKU-BACKPACK-TRAVEL-30L',
    itemName: 'Waterproof Adventure Backpack 30L',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-23T07:30:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-Q7R8S',
    customerName: 'Kavita Reddy',
    customerEmail: 'kavita.reddy@example.com',
    customerPhone: '+91 94321 09876',
    orderId: 'ORD-10013',
    itemSku: 'SKU-SUNGLASSES-POLAR',
    itemName: 'Aviator Polarized UV400 Sunglasses',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'IN_REVIEW',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-23T12:15:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Frame hinge was loose out of the box.',
        createdAt: new Date('2026-08-23T12:30:00Z'),
      },
    ],
  },

  // 3. APPROVED requests (with varied resolutions and valid refund amounts)
  {
    reference: 'RET-2026-T9U1V',
    customerName: 'Suresh Menon',
    customerEmail: 'suresh.menon@example.com',
    customerPhone: '+91 93210 98765',
    orderId: 'ORD-10014',
    itemSku: 'SKU-AIR-PURIFIER-HEPA',
    itemName: 'True HEPA Smart Room Air Purifier',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'APPROVED',
    resolution: 'REFUND',
    refundAmount: 149.99,
    createdAt: new Date('2026-08-18T10:00:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Motor vibration fault confirmed by tech team. Full refund of $149.99 approved.',
        createdAt: new Date('2026-08-18T16:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-W2X3Y',
    customerName: 'Neha Deshmukh',
    customerEmail: 'neha.deshmukh@example.com',
    customerPhone: '+91 92109 87654',
    orderId: 'ORD-10015',
    itemSku: 'SKU-WINTER-JACKET-L',
    itemName: 'Thermal Insulated Puffer Jacket (L)',
    quantity: 1,
    reason: 'SIZE_ISSUE',
    status: 'APPROVED',
    resolution: 'REPLACEMENT',
    refundAmount: null,
    createdAt: new Date('2026-08-18T14:30:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Approved for Size XL replacement. Warehouse pickup scheduled.',
        createdAt: new Date('2026-08-19T11:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-Z4A5B',
    customerName: 'Manish Tiwari',
    customerEmail: 'manish.tiwari@example.com',
    customerPhone: '+91 91098 76543',
    orderId: 'ORD-10016',
    itemSku: 'SKU-GAMING-MOUSE-RGB',
    itemName: 'Ergonomic Optical Gaming Mouse',
    quantity: 1,
    reason: 'NOT_AS_DESCRIBED',
    status: 'APPROVED',
    resolution: 'STORE_CREDIT',
    refundAmount: null,
    createdAt: new Date('2026-08-19T09:15:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Customer opted for store credit instead of waiting for restock.',
        createdAt: new Date('2026-08-19T14:20:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-C6D7E',
    customerName: 'Divya Iyer',
    customerEmail: 'divya.iyer@example.com',
    customerPhone: '+91 99988 12345',
    orderId: 'ORD-10017',
    itemSku: 'SKU-SILK-SAREE-RED',
    itemName: 'Handloom Kanjivaram Silk Saree - Ruby Red',
    quantity: 1,
    reason: 'WRONG_ITEM',
    status: 'APPROVED',
    resolution: 'REFUND',
    refundAmount: 220.00,
    createdAt: new Date('2026-08-19T16:45:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Wrong colorway dispatched. Full refund approved upon return shipment dispatch.',
        createdAt: new Date('2026-08-20T12:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-F8G9H',
    customerName: 'Gaurav Sen',
    customerEmail: 'gaurav.sen@example.com',
    customerPhone: '+91 98877 23456',
    orderId: 'ORD-10018',
    itemSku: 'SKU-ESPRESSO-MACHINE',
    itemName: 'Compact 15-Bar Pump Espresso Coffee Maker',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'APPROVED',
    resolution: 'REPLACEMENT',
    refundAmount: null,
    createdAt: new Date('2026-08-20T11:00:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-J1K2M',
    customerName: 'Shreya Saxena',
    customerEmail: 'shreya.saxena@example.com',
    customerPhone: '+91 97766 34567',
    orderId: 'ORD-10019',
    itemSku: 'SKU-DUFFLE-BAG-LEA',
    itemName: 'Vintage Leather Weekender Duffle Bag',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'APPROVED',
    resolution: 'STORE_CREDIT',
    refundAmount: null,
    createdAt: new Date('2026-08-20T14:10:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Customer accepted store credit bonus voucher.',
        createdAt: new Date('2026-08-21T10:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-N3P4Q',
    customerName: 'Abhishek Roy',
    customerEmail: 'abhishek.roy@example.com',
    customerPhone: '+91 96655 45678',
    orderId: 'ORD-10020',
    itemSku: 'SKU-WIRELESS-EARBUDS',
    itemName: 'True Wireless Active Noise Canceling Earbuds',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'APPROVED',
    resolution: 'REFUND',
    refundAmount: 79.50,
    createdAt: new Date('2026-08-21T09:30:00Z'),
    notes: [],
  },

  // 4. REJECTED requests (Terminal state)
  {
    reference: 'RET-2026-R5S6T',
    customerName: 'Sunita Chawla',
    customerEmail: 'sunita.chawla@example.com',
    customerPhone: '+91 95544 56789',
    orderId: 'ORD-10021',
    itemSku: 'SKU-PERFUME-EDP-100ML',
    itemName: 'Signature Eau De Parfum 100ml',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-16T10:00:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Cosmetics and opened fragrance items are strictly non-returnable under policy section 4.2.',
        createdAt: new Date('2026-08-16T15:30:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-U7V8W',
    customerName: 'Harsh Vardhan',
    customerEmail: 'harsh.vardhan@example.com',
    customerPhone: '+91 94433 67890',
    orderId: 'ORD-10022',
    itemSku: 'SKU-DRONE-4K-GPS',
    itemName: 'Quadcopter 4K Camera Drone with GPS',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-17T09:20:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Telemetry log confirms crash occurred due to user piloting error in restricted altitude.',
        createdAt: new Date('2026-08-17T17:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-X9Y1Z',
    customerName: 'Tarun Agarwal',
    customerEmail: 'tarun.agarwal@example.com',
    customerPhone: '+91 93322 78901',
    orderId: 'ORD-10023',
    itemSku: 'SKU-SWIM-TRUNKS-M',
    itemName: 'Quick-Dry Floral Swim Trunks (M)',
    quantity: 2,
    reason: 'SIZE_ISSUE',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-17T13:00:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Hygiene tag removed. Return request cannot be accepted.',
        createdAt: new Date('2026-08-18T10:15:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-A2B3C',
    customerName: 'Ritu Sen',
    customerEmail: 'ritu.sen@example.com',
    customerPhone: '+91 92211 89012',
    orderId: 'ORD-10024',
    itemSku: 'SKU-SMART-PLUG-WIFI',
    itemName: 'WiFi Smart Plug 16A with Energy Monitor',
    quantity: 3,
    reason: 'NOT_AS_DESCRIBED',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-18T11:30:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Return window expired (request placed 65 days after delivery).',
        createdAt: new Date('2026-08-18T18:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-D4E5F',
    customerName: 'Nitin Khanna',
    customerEmail: 'nitin.khanna@example.com',
    customerPhone: '+91 91100 90123',
    orderId: 'ORD-10025',
    itemSku: 'SKU-TENNIS-RACKET-PRO',
    itemName: 'Graphite Pro Tournament Tennis Racket',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-19T08:45:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Damage determined to be structural impact on court surface, not a manufacturing defect.',
        createdAt: new Date('2026-08-19T16:30:00Z'),
      },
    ],
  },

  // 5. COMPLETED requests (Terminal state, closed out)
  {
    reference: 'RET-2026-G6H7J',
    customerName: 'Amitabh Choudhury',
    customerEmail: 'amitabh.c@example.com',
    customerPhone: '+91 99001 12233',
    orderId: 'ORD-10026',
    itemSku: 'SKU-OFFICE-CHAIR-MESH',
    itemName: 'Ergonomic High-Back Mesh Desk Chair',
    quantity: 1,
    reason: 'DAMAGED',
    status: 'COMPLETED',
    resolution: 'REFUND',
    refundAmount: 189.00,
    createdAt: new Date('2026-08-14T09:00:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Defective gas cylinder reported.',
        createdAt: new Date('2026-08-14T09:30:00Z'),
      },
      {
        authorName: 'Deepak (Lead)',
        content: 'Approved full refund of $189.00.',
        createdAt: new Date('2026-08-15T11:00:00Z'),
      },
      {
        authorName: 'Finance Gateway',
        content: 'Refund credited to original payment method (Txn #REF-889123). Request closed.',
        createdAt: new Date('2026-08-16T14:20:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-K8M9N',
    customerName: 'Radhika Bose',
    customerEmail: 'radhika.bose@example.com',
    customerPhone: '+91 98990 23344',
    orderId: 'ORD-10027',
    itemSku: 'SKU-CARDIGAN-WOOL-M',
    itemName: 'Merino Wool Button Cardigan - Grey (M)',
    quantity: 1,
    reason: 'SIZE_ISSUE',
    status: 'COMPLETED',
    resolution: 'REPLACEMENT',
    refundAmount: null,
    createdAt: new Date('2026-08-15T10:15:00Z'),
    notes: [
      {
        authorName: 'Aarav (Agent)',
        content: 'Replacement item delivered and signed by customer. Case completed.',
        createdAt: new Date('2026-08-17T16:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-P1Q2R',
    customerName: 'Manish Tiwari',
    customerEmail: 'manish.tiwari@example.com',
    customerPhone: '+91 91098 76543',
    orderId: 'ORD-10028',
    itemSku: 'SKU-GAMING-KEYCAPS',
    itemName: 'PBT Double-Shot Custom Keycap Set',
    quantity: 1,
    reason: 'WRONG_ITEM',
    status: 'COMPLETED',
    resolution: 'STORE_CREDIT',
    refundAmount: null,
    createdAt: new Date('2026-08-15T14:00:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Store credit balance updated in customer wallet. Request closed.',
        createdAt: new Date('2026-08-16T10:30:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-S3T4U',
    customerName: 'Kalyan Bannerjee',
    customerEmail: 'kalyan.b@example.com',
    customerPhone: '+91 97889 34455',
    orderId: 'ORD-10029',
    itemSku: 'SKU-ROUTER-WIFI6-AX',
    itemName: 'Dual-Band WiFi 6 Gigabit Router',
    quantity: 1,
    reason: 'NOT_AS_DESCRIBED',
    status: 'COMPLETED',
    resolution: 'REFUND',
    refundAmount: 89.99,
    createdAt: new Date('2026-08-16T08:30:00Z'),
    notes: [
      {
        authorName: 'Finance Gateway',
        content: 'Full refund transaction completed successfully.',
        createdAt: new Date('2026-08-17T11:00:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-V5W6X',
    customerName: 'Anjali Kapoor',
    customerEmail: 'anjali.k@example.com',
    customerPhone: '+91 96778 45566',
    orderId: 'ORD-10030',
    itemSku: 'SKU-FITNESS-BAND-HR',
    itemName: 'Waterproof Heart Rate Activity Tracker',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'COMPLETED',
    resolution: 'STORE_CREDIT',
    refundAmount: null,
    createdAt: new Date('2026-08-16T12:45:00Z'),
    notes: [],
  },
  {
    reference: 'RET-2026-Y7Z8A',
    customerName: 'Sanjay Malhotra',
    customerEmail: 'sanjay.m@example.com',
    customerPhone: '+91 95667 56677',
    orderId: 'ORD-10031',
    itemSku: 'SKU-THERMOS-FLASK-1L',
    itemName: 'Stainless Steel Insulated Vacuum Flask 1L',
    quantity: 2,
    reason: 'DAMAGED',
    status: 'COMPLETED',
    resolution: 'REPLACEMENT',
    refundAmount: null,
    createdAt: new Date('2026-08-17T10:00:00Z'),
    notes: [
      {
        authorName: 'Sara (Support)',
        content: 'Replacement units delivered in pristine condition. Request finalized.',
        createdAt: new Date('2026-08-19T15:00:00Z'),
      },
    ],
  },

  // 6. Soft-deleted requests (demonstrating soft removal without data destruction)
  {
    reference: 'RET-2026-DEL01',
    customerName: 'Siddharth Roy',
    customerEmail: 'sid.roy@example.com',
    customerPhone: '+91 94556 67788',
    orderId: 'ORD-10032',
    itemSku: 'SKU-PEN-SET-LUX',
    itemName: 'Luxury Fountain Pen Gift Set',
    quantity: 1,
    reason: 'CHANGED_MIND',
    status: 'OPEN',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-12T09:00:00Z'),
    deletedAt: new Date('2026-08-13T10:00:00Z'),
    notes: [
      {
        authorName: 'Support Agent',
        content: 'Customer called to cancel return request; keeping item.',
        createdAt: new Date('2026-08-13T09:59:00Z'),
      },
    ],
  },
  {
    reference: 'RET-2026-DEL02',
    customerName: 'Meenakshi Sundaram',
    customerEmail: 'meenakshi.s@example.com',
    customerPhone: '+91 93445 78899',
    orderId: 'ORD-10033',
    itemSku: 'SKU-BLUETOOTH-SPEAKER',
    itemName: 'Portable Waterproof Bluetooth Speaker',
    quantity: 1,
    reason: 'WRONG_ITEM',
    status: 'REJECTED',
    resolution: null,
    refundAmount: null,
    createdAt: new Date('2026-08-13T11:00:00Z'),
    deletedAt: new Date('2026-08-14T14:00:00Z'),
    notes: [
      {
        authorName: 'Deepak (Lead)',
        content: 'Archived duplicate ticket after rejection.',
        createdAt: new Date('2026-08-14T13:50:00Z'),
      },
    ],
  },
];

async function main() {
  console.log('🌱 Starting ReturnDesk database seed...');

  // Clear existing records in a safe order
  await prisma.note.deleteMany({});
  await prisma.returnRequest.deleteMany({});

  console.log(`Clearing existing records complete.`);
  console.log(`Inserting ${SAMPLE_REQUESTS.length} return requests with realistic notes...`);

  for (const item of SAMPLE_REQUESTS) {
    const { notes, ...requestData } = item;

    await prisma.returnRequest.create({
      data: {
        ...requestData,
        notes: {
          create: notes,
        },
      },
    });
  }

  const totalCount = await prisma.returnRequest.count();
  const activeCount = await prisma.returnRequest.count({
    where: { deletedAt: null },
  });
  const notesCount = await prisma.note.count();

  console.log(`✅ Seeding finished successfully!`);
  console.log(`📊 Total Requests created: ${totalCount} (${activeCount} active, ${totalCount - activeCount} soft-removed)`);
  console.log(`📝 Total Notes created: ${notesCount}`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
